name: Publish Docker image
on: push
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Container Registry
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR }}
          registry: ghcr.io
          repository: gliwka/centos6-devtoolset7
          tag_with_ref: true
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR }}
          registry: docker.pkg.github.com
          repository: gliwka/centos6-devtoolset7-docker/centos6-devtoolset7
          tag_with_ref: true
